### ISSUE TITLE
Progress.Circle percent text not change

### ISSUE THREAD

**Issue by fluvios** [oblador/react-native-progress#104]
hello, i try using this library for displaying my money progress. but why the text in progress.circle still 0% ?

**Comment by LolnationCH** [comment]
Using something like this : 
```JS
<Progress.Circle size={30}
                         showsText={true}
                         size={150}
                         progress={this.state.progress}
                         borderWidth={0}
                         color={'rgb(0, 255, 25)'}
                         unfilledColor={'rgb(121, 119, 119)'}/>
```
Don't forget to use ``this.setState()`` to change ``this.state.progress``!

Also, if you want to show decimal on your progress, change ``Circle.js formartText`` to 
``formatText: progress => `${(progress * 100).toFixed(NumberOfDigit)}%`,`` 

If it's not working, share the important part of your code.

**Comment by LolnationCH** [comment]
try something like this :
```JavaScript

constructor(props) {
    super(props);
    this.state = {percent: 0};
  }
render(){
    return(
        <Progress.Circle progress={this.state.percent} size={50} showsText={true} color={color.lightColor} />
         <TextInput
            style={styles.textInput}
            keyboardType='numeric'
            placeholder="Percent %"
            onChangeText={(percent ) => this.setState({percent : percent / 100})}/>
     );
}
```

**Comment by mutiadianita** [comment]
I also happen to mine, I set the progress=0.25 but the text still 0%

**Comment by mutiadianita** [comment]
It solved by changing
{formatText(progressValue)}

in line 187 at Circle.js (node_modules\react-native-progress\Circle.js) to

{progress ? formatText(progress._value) : this.forceUpdate()}

I follow the answer from this issue
[#Issue67](https://github.com/oblador/react-native-progress/issues/67)

**Comment by ckOfor** [comment]
```
state = {
    percentage: 80,
  }

<Progress.Circle
                size={82}
                borderWidth={1}
                color={'#2AE596'}
                unfilledColor={'#303030'}
                borderColor={'#303030'}
                progress={this.state.percentage / 100}
                animated
                showsText
                formatText={() => {
                  return `${this.state.percentage}%`
                }}
              />

```

**Comment by bryanprimus** [comment]
setting `animated` to `false` seems to fix the issue
