### ISSUE TITLE
when i import `react-native-progress`, throw this error `undefined is not an object(evaluating 'undefined.hex')`

### ISSUE THREAD

**Issue by BluePecker** [oblador/react-native-progress#108]
- [√ ] I have reviewed the [documentation](https://facebook.github.io/react-native)
- [√ ] I have searched [existing issues](https://github.com/facebook/react-native/issues)
- [√] I am using the [latest React Native version](https://github.com/facebook/react-native/releases)

## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

Packages: (wanted => installed)
  react: ^16.3.1 => 16.3.1
  react-native: ^0.55.2 => 0.55.2

## Steps to Reproduce

import Progress from 'react-native-progress';

## Expected Behavior

run success

## Actual Behavior

![image](https://user-images.githubusercontent.com/28583275/38712706-fb79058a-3eff-11e8-99dc-f1969adef172.png)

**Comment by jmullings** [comment]
Are you using yarn as a package manager?

**Comment by BluePecker** [comment]
the problem is due to the fact that react-native import `art`

**Comment by noudadrichem** [comment]
But it is not fixed? So why is this closed? Facing the same issue 😝

**Comment by AylwSt01** [comment]
facing the same issue!

**Comment by annygutierrez** [comment]
> the problem is due to the fact that react-native import `art`

This was the solution for me

**Comment by pk936** [comment]
@annygutierrez how did you solve. You should tell steps for others too.

**Comment by pk936** [comment]
I resoved it by manual linking the library @react-native-community/art:

react-native link @react-native-community/art

**Comment by d-baranowski** [comment]
I just had to install art 
```yarn add react-native-community/art```
