### ISSUE TITLE
Circle components weird rotating

### ISSUE THREAD

**Issue by emretekince** [oblador/react-native-progress#11]
Hi,

As you may see on the screenshots, Progress.Circle component rotating weirdly..

<img width="112" alt="ekran resmi 2016-06-05 11 45 53" src="https://cloud.githubusercontent.com/assets/5754074/15804504/7ea6e13c-2b13-11e6-82ce-b22ed875fbb2.png">
<img width="125" alt="ekran resmi 2016-06-05 11 45 57" src="https://cloud.githubusercontent.com/assets/5754074/15804505/835e25aa-2b13-11e6-8dc3-fca8bfba5235.png">
<img width="124" alt="ekran resmi 2016-06-05 11 46 02" src="https://cloud.githubusercontent.com/assets/5754074/15804507/875181d4-2b13-11e6-886b-d1cf7a7aa32c.png">

**Comment by oblador** [comment]
My guess would be that you've applied some styling that causes it. Can you provide a code sample on how you use it?

**Comment by luisfuertes** [comment]
+1 when put <Text> in same View, i solved it moving text to other <View>

**Comment by oblador** [comment]
@luisfuertes Would love some code to reproduce the bug.

**Comment by luisfuertes** [comment]
I tried to reproduce it but I could not. Now it works well

**Comment by KevinHu2014** [comment]
Same Problem .
`<View style={{flex: 1,}}>
          <Text>{'UID'+this.state.UID}</Text>
           <Progress.Circle
            progress={this.state.progress}
            indeterminate={this.state.indeterminate}
            direction="counter-clockwise"
          />
      </View>`

**Comment by fimbit** [comment]
set the container view style : {justifyContent: 'center',alignItems: 'center',} can fix this

**Comment by danleveille** [comment]
Same issue happened to me, but @fimbit's suggestion fixed it.

**Comment by PaulBGD** [comment]
How to reproduce: don't pass a width/height in styles to the circle. After explicitly setting the height/width, the circle stops spinning. I think it has something to do with taking up all the space in a flex'd view or something.

**Comment by oblador** [comment]
Hi guys, I think this should be fixed in 3.2.0. Can anybody confirm?

**Comment by oblador** [comment]
Closing this in lack of responses an as it should be fixed.
