### ISSUE TITLE
No component found for view with name "ARTShape"

### ISSUE THREAD

**Issue by gabrielmoncea** [oblador/react-native-progress#127]
Greetings,

I installed the ReactART based components trough CocoaPods and it throws me this error when going to the components page.

<img width="453" alt="screen shot 2018-09-11 at 11 20 24 am" src="https://user-images.githubusercontent.com/39256258/45347461-d52c6f80-b5b4-11e8-85f4-56331e9d6e5b.png">

```
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-progress": "^3.5.0",
```

**Comment by damathryx** [comment]
i have the same issue. tried pod install and pod update. still have this error

**Comment by yesmesalman** [comment]
Add the ART.xcodeproj (found in node_modules/react-native/Libraries/ART) to the Libraries group and add libART.a to Link Binary With Libraries under Build Phases.

**Comment by PavanKumar-sa** [comment]
React native migration 0.60 throwing error "No component found for view with name ARTShape"
Default pod file of react doesn't contain ART.

![Simulator Screen Shot - iPhone 6 - 2019-07-18 at 15 54 56](https://user-images.githubusercontent.com/41342612/61454134-a83bac80-a97d-11e9-8198-40eaced21f17.png)

**Comment by shouhuori** [comment]
+1

**Comment by PavanKumar-sa** [comment]
For react native >= 0.60 for ARTShape component not found issue:

1. Open Podfile and add below given path and save the file
    

> pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART' 


2. From your root folder navigate to ios folder of the app:  
    

> cd ios

3. now inside ios folder

> pod install 

4. Close existing metro bundler ,close Xcode 
5. Run metro bundler, open Xcode > clean build folder and Build.

This will work !!!

**Comment by vivekkadu** [comment]
> For react native >= 0.60 for ARTShape component not found issue:
> 
> 1. Open Podfile and add below given path and save the file
> 
> > pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
> 
> 1. From your root folder navigate to ios folder of the app:
> 
> > cd ios
> 
> 1. now inside ios folder
> 
> > pod install
> 
> 1. Close existing metro bundler ,close Xcode
> 2. Run metro bundler, open Xcode > clean build folder and Build.
> 
> This will work !!!

Work for me Thanks @PavanKumar-sa

**Comment by jhainaua** [comment]
I did this, but now I'm getting a build error 'fb/visibility.h' file not found. Any ideas?

**Comment by andylala-cust** [comment]
> For react native >= 0.60 for ARTShape component not found issue:
> 
> 1. Open Podfile and add below given path and save the file
> 
> > pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
> 
> 1. From your root folder navigate to ios folder of the app:
> 
> > cd ios
> 
> 1. now inside ios folder
> 
> > pod install
> 
> 1. Close existing metro bundler ,close Xcode
> 2. Run metro bundler, open Xcode > clean build folder and Build.
> 
> This will work !!!

**Comment by anton-matosov** [comment]
I had to add `'ART'` to subsepcs of React pod
```
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'ART', # <--- Add this entry
    'Core',
    'CxxBridge',
 ...
]

**Comment by krishan-kumar-mourya** [comment]
> For react native >= 0.60 for ARTShape component not found issue:
> 
> 1. Open Podfile and add below given path and save the file
> 
> > pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
> 
> 1. From your root folder navigate to ios folder of the app:
> 
> > cd ios
> 
> 1. now inside ios folder
> 
> > pod install
> 
> 1. Close existing metro bundler ,close Xcode
> 2. Run metro bundler, open Xcode > clean build folder and Build.
> 
> This will work !!!

This worked for me. Thanks :)
