### ISSUE TITLE
Progress bar fill width starts somewhere in the middle

### ISSUE THREAD

**Issue by jozedavid** [oblador/react-native-progress#139]
Hello, my first question here, I am using the Progress.Bar, but the fill starts somewhere in the middle.

![screen shot 2019-01-29 at 11 06 28 am](https://user-images.githubusercontent.com/5778748/51921741-036ce900-23b6-11e9-962d-2434bacef1d3.png)

I have the progress on 0.1, when I set this on 1 the fill is complete.

the code:
`<ProgressBar 
 color={Colors.bright_red_mct}
 unfilledColor={Colors.grey_gainsboro}
 borderWidth={3}
 height={6}
 borderColor={Colors.grey_gainsboro}
 borderRadius={8}
 progress={0.1}
 style={{ flex:1 }}
/>`

I guess the problem is the flex, hope you can help me, thanks...

**Comment by joakimalbert** [comment]
@jozedavid did you solve it? Have the same issue

**Comment by cloudy-ninja** [comment]
@jozedavid please help me.
I got the same issue.

**Comment by DillionApple** [comment]
Same here.

**Comment by jozedavid** [comment]
We had to make our own component to achieve what we wanted, here is the code:

`render() {
    var value = false
    var valueBalloon = false
    var infoText = null; 

    switch (this.props.valueStyle) {
      case 'icon':
        valueIcon = (
          <View style={styles.flexBox}>
            <View style={[{flex:this.state.progress}]}>
              <View style={styles.progressBar__balloon}>
                {this.state.progress > 0 && 
                  <Text style={styles.progressBar__balloonVal}>{this.state.progress}%</Text> 
                }
                <Image source={require('assets/marker-truck-icon-progressbar.png')} style={styles.progressIcon} />
              </View>
            </View>
            <View style={[{flex:100 - this.state.progress}]}></View>
          </View>
        )
        break
      default:
        break
    }

    infoText = (
      <Text>{this.state.text}</Text> 
    )

    var chart = (
      <View>
        {this.state.text && 
          infoText
        }
        <View style={[styles.flexBox, styles.progressBar]}>
          <View style={[styles.progressBar_left, {flex:this.state.progress}]} />
          <View style={[styles.progressBar_right, {flex:100 - this.state.progress}]}></View>
        </View>
        {valueIcon}
      </View>
    )
    return chart
  }`

**Comment by tahir-jamil** [comment]
@jozedavid  Hey Please help us to solve this bug that showing completed part in the middle instead of start from left extreme

**Comment by FerrisYufuWang** [comment]
![fixed](https://user-images.githubusercontent.com/19471386/63151131-5dc05500-c03b-11e9-86c7-dc3fd6682020.png)

Modify **Bar.js line 6** can fix this problem
before:
`const BAR_WIDTH_ZERO_POSITION =
  INDETERMINATE_WIDTH_FACTOR / (1 + INDETERMINATE_WIDTH_FACTOR);`
after:
`const BAR_WIDTH_ZERO_POSITION = 0;`

**Comment by femiveys** [comment]
@FerrisYufuWang This doesn't work for me.
Is there a setting or so to define where the progress bar starts?

**Comment by Diwei-Chen** [comment]
https://github.com/oblador/react-native-progress/issues/139#issuecomment-521916908 doesn't work for me as well.

**Comment by FerrisYufuWang** [comment]
@femiveys i think so

**Comment by SimonPotier** [comment]
Got the same problem, any suggestion on how to solve this ?

**Comment by Sanan4li** [comment]
I think there is no way to solve this.. I am facing the same issue and I have tried a lot but no success.

**Comment by ahmadsyamim** [comment]
I solved this using 

```
import {Dimensions} from "react-native";
import ProgressBar from "react-native-progress/Bar";
const barWidth = Dimensions.get("screen").width;
<ProgressBar progress={0.1} width={barWidth} height={2} borderRadius={0}/>
```
