### ISSUE TITLE
App runs on xcode but not with "react-native run-ios"

### ISSUE THREAD

**Issue by PedroFonseca17** [oblador/react-native-progress#142]
So, on my app i've installed it and linked to ios. If i run the app on xcode it works, and shows the progress circle. But if i try to run the app with "react-native run-ios" it says "No component found for view with the name "ARTShape". I've restarted xcode, my computer, the simulator and nothing seems to help, have you guys seen anything like this? And how can i fix it?

**Comment by gmajali** [comment]
Any updates?
