### ISSUE TITLE
CocoaPods could not find compatible versions for pod "React/ART"

### ISSUE THREAD

**Issue by billtlee** [oblador/react-native-progress#161]
I just upgraded to react native 6 and when I added

pod 'React', path: '../node_modules/react-native', subspecs: ['ART',]

to my pod file and run pod install, I got the following error:

[!] CocoaPods could not find compatible versions for pod "React/ART":
  In Podfile:
    React/ART (from `../node_modules/react-native`)

None of your spec sources contain a spec satisfying the dependency: `React/ART (from `../node_modules/react-native`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by ricbermo** [comment]
I was having that issue with RN 60. I just installed @react-native-community/art, run `pod install` inside my `ios/` folder and did a deep import `import CircleSnail from "react-native-progress/CircleSnail";`

**Comment by nkhoshini** [comment]
Worked for me by adding 
```pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'``` 

and then running `pod install`

**Comment by Martan-Toupchi** [comment]
> Worked for me by adding
> `pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'`
> 
> and then running `pod install`

It worked for me, Thanks mate

**Comment by rickmrobin** [comment]
You saved my day.

**Comment by rickmrobin** [comment]
> Worked for me by adding
> `pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'`
> 
> and then running `pod install`

You saved my day

**Comment by mayconmesquita** [comment]
I had to include this:

pod 'React', path: '../node_modules/react-native', subspecs: [
      'ART',
]

save, then `pod install`

**Comment by rahsheen** [comment]
Just for anyone else running across this. Adding the subspec did _not_ work for me with RN 0.60.5, but adding `pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'` to my Podfile did the trick. 

I would guess the alternative of installing @react-native-community/art would also do the trick, but I did not try it.

**Comment by draperunner** [comment]
Just to clarify that on React Native 0.60 you don't just _add_ the React-ART pod, but you don't need to use the subspec that is mentioned in the README.

Updated installation instructions:

### For CocoaPod users:

If using React Native >= 0.60, add the React-ART pod to your Podfile:
```
pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
```

If using React Native <= 0.59, add the ART subspec like so:
```
pod 'React', path: '../node_modules/react-native', subspecs: [
  'ART',
]
```
Remember to run `pod install` after these changes.

**Comment by prasannavenkatesh-colan** [comment]
> Worked for me by adding `pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'`
> 
> and then running `pod install`

[!] No podspec found for `React-ART` in `../node_modules/react-native/Libraries/ART`

**Comment by Vanne04** [comment]
hi, when i run this command pod install, it shows me the following error:
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[!] Your Podfile requires that the plugin `cocoapods-art` be installed. Please install it and try installation again.

but i installed cocoapods-art.

**Comment by oblador** [comment]
This library is not using ART anymore, but RN SVG.
