### ISSUE TITLE
Incorrect position

### ISSUE THREAD

**Issue by yutin1987** [oblador/react-native-progress#17]
https://youtu.be/pwe0b6H1xoE

**Comment by yutin1987** [comment]
maybe, can setting transform-origin in the feature.
https://github.com/facebook/react-native/issues/1964

fixed it, add `{width, height}` into https://github.com/oblador/react-native-progress/blob/master/makeAnimatable.js#L103

**Comment by chirag04** [comment]
@oblador I can confirm the same behavior.

**Comment by chirag04** [comment]
ok this is duplicate of https://github.com/oblador/react-native-progress/issues/11

**Comment by oblador** [comment]
Closing duplicate
