### ISSUE TITLE
Tried to register two views with the same name ARTSurfaceView

### ISSUE THREAD

**Issue by simon-sou** [oblador/react-native-progress#176]
when use both ART and this react-native-progress. 

![image](https://user-images.githubusercontent.com/48339364/67932228-6a962300-fbfe-11e9-9dda-feadbd1ae8ba.png)

my version
` "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "0.59.9",
 "react-native-progress": "^4.0.1"`
platform:android

**Comment by yehancha** [comment]
Having the same issue here. This is my package.json dependencies:
`"dependencies": {
    "@expo/vector-icons": "^6.3.1",
    "appcenter": "^1.5.1",
    "appcenter-analytics": "^1.5.1",
    "appcenter-crashes": "^1.5.1",
    "crypto-js": "^3.1.9-1",
    "eslint": "^4.19.1",
    "moment": "^2.22.2",
    "native-base": "^2.6.1",
    "prop-types": "^15.6.2",
    "react": "16.8.3",
    "react-native": "0.59.10",
    "react-native-af-video-player": "^0.2.1",
    "react-native-audio-file-streamer": "0.0.5",
    "react-native-auth0": "^1.6.0",
    "react-native-circular-progress": "^1.0.0",
    "react-native-collapsible": "^0.12.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-document-picker": "^2.1.0",
    "react-native-easy-grid": "^0.2.0",
    "react-native-elements": "^0.19.1",
    "react-native-fbsdk": "^0.10.0",
    "react-native-firebase": "^4.3.8",
    "react-native-gifted-chat": "^0.4.3",
    "react-native-google-places-autocomplete": "^1.3.6",
    "react-native-image-picker": "^0.26.10",
    "react-native-image-view": "^2.0.5",
    "react-native-keyboard-aware-scroll-view": "^0.6.0",
    "react-native-loader": "^1.2.1",
    "react-native-multiple-tags": "0.0.4",
    "react-native-permissions": "^2.0.2",
    "react-native-popover-tooltip": "^1.1.4",
    "react-native-progress": "^4.0.1",
    "react-native-snap-carousel": "^3.7.2",
    "react-native-sound-level": "^1.1.5",
    "react-native-svg": "^6.4.1",
    "react-native-swipe-gestures": "^1.0.2",
    "react-native-swiper": "^1.5.13",
    "react-native-transition": "^1.1.8",
    "react-native-vector-icons": "^4.6.0",
    "react-native-video": "^4.0.0",
    "react-native-youtube": "^1.1.0",
    "react-navigation": "^2.5.5",
    "rn-fetch-blob": "^0.10.13"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "jetifier": "^1.6.4",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3"
  },`

**Comment by johnryan** [comment]
@simon-sou did you find a solution to this other than downgrading?

**Comment by keremcubuk** [comment]
> Had the same issue with the version 4.0.1 (on RN 0.59.10). Downgrading to version 3.6.0 fixed the issue.
> 
> I think the following point in the [4.0.0 release note](https://github.com/oblador/react-native-progress/releases/tag/v4.0.0) has a clue.
> 
> > BREAKING: Migrated to RNC ART library to support RN 0.60+

It works! Thanks a lot 😄

**Comment by 337240552** [comment]
Not work for RN 0.61.4

**Comment by TunvirRahman** [comment]
Having the same issue in **RN 0.61.5**

**Comment by PrantikMondal** [comment]
Why this issue is closed? Still issue is there in **RN 0.61.5** version and **react-native-progress: 4.0.3**.

**Comment by hsource** [comment]
The problem is not with this library. It happens when you have multiple versions of `@react-native-community/art` installed.

For example, I installed this library, and then later installed a library that required `@react-native-community/art@^1.2.0`. My `yarn.lock` looked like this:

```
"@react-native-community/art@^1.0.1", "@react-native-community/art@^1.1.2":
  version "1.1.2"
  resolved "https://registry.yarnpkg.com/@react-native-community/art/-/art-1.1.2.tgz#8d365ad5a12f83a0570ef83590f883a201f8e723"
  integrity sha512-KCPWdrdkjMOjUjKjYhJUt628mjf+SyoopXPztFbPvSpMl6jI9Qs8fnxnrt8ITKJvt7Xy7K7y6Cn/Q5h1GgIwjQ==
  dependencies:
    art "^0.10.3"
    invariant "^2.2.4"
    prop-types "^15.7.2"

"@react-native-community/art@^1.2.0":
  version "1.2.0"
  resolved "https://registry.yarnpkg.com/@react-native-community/art/-/art-1.2.0.tgz#386d95393f6042d9006f9d4bc6063fb898794460"
  integrity sha512-a+ZcRGl/BzLa89yi33Mbn5SHavsEXqKUMdbfLf3U8MDLElndPqUetoJyGkv63+BcPO49UMWiQRP1YUz6/zfJ+A==
  dependencies:
    art "^0.10.3"
    invariant "^2.2.4"
    prop-types "^15.7.2"
```

To fix this, just delete the earlier versions (the block with `version "1.1.2"`) and then do a `yarn install` to have everything use the same version of art.

**Comment by otikindriyana** [comment]
`"@react-native-community/art@^1.2.0":
  version "1.2.0"
  resolved "https://registry.yarnpkg.com/@react-native-community/art/-/art-1.2.0.tgz#386d95393f6042d9006f9d4bc6063fb898794460"
  integrity sha512-a+ZcRGl/BzLa89yi33Mbn5SHavsEXqKUMdbfLf3U8MDLElndPqUetoJyGkv63+BcPO49UMWiQRP1YUz6/zfJ+A==
  dependencies:
    art "^0.10.3"
    invariant "^2.2.4"
    prop-types "^15.7.2"`

@hsource still same error :(

**Comment by finik-htec** [comment]
Hey @otikindriyana, as you can see, you have two different versions of @react-native-community/art, because installed version 1.2.0, but react-native-progress is using 1.1.2, so in order to fix that, you need to install @react-native-community/art with version of 1.1.2. I had same issue, and using same version fixed for me.

P.S. look at your package.json, if you have ^1.1.2, it will still install 1.2.0, so you have to use hardcoded version or maybe replace ^ with ~.
