### ISSUE TITLE
CircleSnail no longer working in 4.0.0

### ISSUE THREAD

**Issue by sdeleon28** [oblador/react-native-progress#177]
`CircleSnail` disappeared from an app that was using it when I updated to `4.0.0` - even after updating the import syntax to `import * as Progress from 'react-native-progress';`.

I've created a minimal Expo app to demonstrate that it doesn't work. I've copied a simplified version of the code from the `Example` folder. Here's the repo -> https://github.com/sdeleon28/react-native-progress-minimal-repro

**Comment by oblador** [comment]
Hi, it's due to a known bug in ART. See this thread for more info: https://github.com/oblador/react-native-progress/issues/173 Hopefully the fix will be merged soon

**Comment by oblador** [comment]
This should be fixed now. Closing
