### ISSUE TITLE
Progress.Circle not working on iOS

### ISSUE THREAD

**Issue by vinc-labs** [oblador/react-native-progress#178]
I'm facing a problem: when using Progress.Circle, it's working only on android, and ios not showing anything. I don't know why, but i try draw a line by @react-native-community/art it's also the same problem. Can anyone help me?? Sorry about my poor English :((

**Comment by akinncar** [comment]
Same issue after upgrades React Native 0.42 to 0.59, work's fine in Android.

I tried to install and link libART in iOS but nothing change.

**Comment by rheng001** [comment]
Running into the same issue

**Comment by oblador** [comment]
Please try with:
```
"react-native-progress": "^4.0.2",
"@react-native-community/art": "^1.0.3",
```

**Comment by duythanhcn** [comment]
Circle and CircleSnail are also not working in android too,
I think this problem is came from ART lib
![Screen Shot 2019-11-18 at 4 05 54 PM](https://user-images.githubusercontent.com/13749883/69043252-4ff8e200-0a25-11ea-9e98-5f199ecd89fd.png)

**Comment by akinncar** [comment]
Downgrade to `    "react-native-progress": "^3.6.0"` works for me.

**Comment by gulyaev-fusion** [comment]
@akinncar 
![image](https://user-images.githubusercontent.com/47102562/69336847-82e2e600-0c70-11ea-9bf5-d777f7cfcc42.png)
I try to downgrade, and I set animated = true,  but I have problem
===
Append screenshot

**Comment by akinncar** [comment]
@gulyaev-fusion In my case, I remove @react-native-community/art and don't use animated prop

**Comment by vinc-labs** [comment]
> Please try with:
> 
> ```
> "react-native-progress": "^4.0.2",
> "@react-native-community/art": "^1.0.3",
> ```

Thanks, it's works for me. Will I close this issue please?? :)))

**Comment by vinc-labs** [comment]
I think it's bugs about version, so I closed this issue!
