### ISSUE TITLE
Can you embed content in this?

### ISSUE THREAD

**Issue by tarang9211** [oblador/react-native-progress#18]
Is there a way to appropriately embed content within a 

```js
<Progress.Circle>

</Progress.Circle>
```

**Comment by oblador** [comment]
Yes, anything you put in as children will be passed down.

**Comment by tarang9211** [comment]
Hmm not sure why this is occuring. 
<img width="231" alt="screen shot 2016-08-01 at 1 30 12 am" src="https://cloud.githubusercontent.com/assets/5876249/17278978/8df3e5fe-5787-11e6-88b9-9b5fe65a295b.png">

```
<Progress.Circle
            size = { 150 }
            style={styles.progress}
            progress={this.state.progress}
            indeterminate={this.state.indeterminate}
          >
            <Text>Test</Text>
          </Progress.Circle>
```

**Comment by tarang9211** [comment]
Gotcha, thanks! Thats what I thought. Thanks for your help @oblador

**Comment by NySiya** [comment]
@oblador, I have followed your solution above but it still didn't work. :+(
