### ISSUE TITLE
Doesn't work in Expo SDK36

### ISSUE THREAD

**Issue by sungsong88** [oblador/react-native-progress#183]
Can't use it. Both iOS and Android crashes.
```
Invariant Violation: requireNativeComponent: "ARTShape" was not found in the UIManager.
```

**Comment by duylinhdang1998** [comment]
how to fix that?

**Comment by lbornov2** [comment]
Happens on iOS only for me:
```
    "react-native-progress": "^4.0.1",
    "react-native-progress-circle": "^2.1.0",
```

Anyone have a solution?

**Comment by mrikirill** [comment]
`
yarn add @react-native-community/art
react-native link @react-native-community/art
cd ios
`

**Comment by duylinhdang1998** [comment]
> You could try this:
> 
> yarn add @react-native-community/art
> react-native link @react-native-community/art
> cd ios && pod install
> re-build project

sdk36 expo cli not react native cli 
can't link

**Comment by sungsong88** [comment]
@duylinhdang1998 +1

**Comment by mrikirill** [comment]
I use 'react-native link' command without any problems in my expo (ejected) project. I've fixed this issue with 'ARTShape' in my expo projected when I've upgraded from SDK34 -> SDK36

**Comment by oblador** [comment]
Expo docs claim they have ART built in, but maybe it's time to rethink the choice of vector rendering library now that it's been janked from core.

**Comment by ivansenic** [comment]
Confirmed by us as well. Only IOS. Here is expo env info:

```
  Expo CLI 3.11.1 environment info:
    System:
      OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.17.0 - /usr/bin/node
      npm: 6.11.3 - /usr/bin/npm
    npmPackages:
      @types/react: ~16.9.0 => 16.9.16 
      @types/react-native: ~0.60.23 => 0.60.25 
      @types/react-navigation: ^3.0.7 => 3.0.7 
      expo: ^36.0.0 => 36.0.1 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.11.1
```

**Comment by kennylbj** [comment]
+1

**Comment by bucktower** [comment]
[Expo docs address this issue in react-native-progress](https://docs.expo.io/versions/latest/sdk/art/) specifically with examples of how to get around it using vector if you want to stay in Managed Workflow

**Comment by Aakashsajjad095** [comment]
use this command in cmd for ART-SHAPE on expo
npm install @react-native-community/art --save

**Comment by dagan-arbox** [comment]
> use this command in cmd for ART-SHAPE on expo
> npm install @react-native-community/art --save

none of the above solved the issue, Expo has any bug fix on this?

**Comment by ajgrowney** [comment]
Error I was running into was:
```
 web  Failed to compile.
C:/path/node_modules/react-native/Libraries/StyleSheet/processColor.js
Module not found: Can't resolve '../Utilities/Platform' in 'C:\path\node_modules\react-native\Libraries\StyleSheet'
```

**Comment by brentvatne** [comment]
> Expo docs claim they have ART built in, but maybe it's time to rethink the choice of vector rendering library now that it's been janked from core.

yeah we removed ART from expo managed apps and updated our docs accordingly: https://docs.expo.io/versions/latest/sdk/art/

we don't plan to include it because it is not really maintained and its functionality can be achieved in a more standard way using svg

**Comment by oblador** [comment]
I’ll accept a PR migrating to the svg lib. Reason I went with ART to begin with was ease of integration which is now lost anyways and we’re just stuck with the bugs.

**Comment by itsashis4u** [comment]
Hi @oblador, I'm new to open source and I haven't used the library. But I'll be happy to try and migrate it to `react-native-svg`

**Comment by duylinhdang1998** [comment]
Hi, I can't use it in Expo 
I got error No Component found for view with name "ART Shape"

**Comment by frw** [comment]
@oblador I've submitted a PR migrating to react-native-svg and it should resolve this issue. Do take a look! #229
