### ISSUE TITLE
Error while updating property 'stroke' in shadow node of type: ARTShape

### ISSUE THREAD

**Issue by anpct** [oblador/react-native-progress#194]
I have tried all the solutions updating to latest versions and also downgrading to previous versions but not able to fix this.

Is this issue solved using react-native link? (my RN = 0.61.5 )
I am currently using expo so that's the only thing i have not tried yet.

my expo version is "expo": "^36.0.0",

**Comment by anpct** [comment]
This is an issue with expo.

**Comment by iyogeshjoshi** [comment]
I don't think that is the case, I'm not using expo and I'm still getting same error

**Comment by karlosintic** [comment]
Has this been resolved? I'm getting the same error using expo.

**Comment by subinsuresh** [comment]
I am also getting the same error on Android, How it is closed?
