### ISSUE TITLE
React Native v0.62 requires useNativeDriver to be explicitly declared

### ISSUE THREAD

**Issue by cmmartin** [oblador/react-native-progress#196]
This is the warning I am getting...

```
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false` in withAnimation(ProgressCircle)
```

`withAnimation.js` needs to be updated. Happy to send a PR, but am I correct that `useNativeDriver` cannot be `true` since we are using `react-native-art`?

**Comment by sayem314** [comment]
Yes, kinda annoying because of constant warnings...

**Comment by dimatretyak** [comment]
> Yes, kinda annoying because of constant warnings...

Just simple workaround for hiding an annoying warning

```javascript
YellowBox.ignoreWarnings(['Animated: `useNativeDriver` was not specified']);
```

**Comment by sayem314** [comment]
Yeah did that a while ago. Thank you :)

**Comment by ajpaulingalls** [comment]
yep, lots of warnings popping up for me as well, easy to hide in UI, but its destroying my logs...

**Comment by dimatretyak** [comment]
In versions 4.1.1 and 4.1.2 it was fixed

**Comment by cmmartin** [comment]
Confirmed this is resolved in the latest
