### ISSUE TITLE
Invariant violation: requireNativeComponent: "ARTShape" was not found in the UIManager

### ISSUE THREAD

**Issue by irajwani** [oblador/react-native-progress#199]
RN version: 0.61.5
r-n-progress: 4.1.0
r-n-image-progress: 1.1.1

Hi, I am facing a red box error (specified in title above). I used the regular require method and the 'deep' require method (import ProgressCircleSnail from 'react-native-progress/CircleSnail';), yet this error will not go away. I was thinking this might be an issue with r-n-svg but that lib is correctly integrated.

Please help!

**Comment by baotoan1905** [comment]
Same issue with react-native 0.60.0, react-native-progress 4.1.1

**Comment by baotoan1905** [comment]
@irajwani  I was able to make it work by follow instruction in readME, install ART lib
![image](https://user-images.githubusercontent.com/7258479/78650094-a2f60780-78e8-11ea-9fc2-ceeaac5b5270.png)

**Comment by irajwani** [comment]
I apologize for the delay in the follow-up. I installed "@react-native-community/art" and then did cd ios && pod install, but even with this package within my project, I still get the exact same error. Is there anything you did after installing "@react-native-community/art"?

**Comment by irajwani** [comment]
Hi, any updates here?

**Comment by itsashis4u** [comment]
Try this:
Add this line to `ios/Podfile`
```pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'```
And the pod install inside the `ios` folder

**Comment by irajwani** [comment]
@itsashis4u It worked, even though it doesn't make sense why as I was already using v1.2.0 of the pod ReactNativeART, but after placing the line in the pod file anyway as per your instruction, and running pod install, no new pod was installed, which makes sense given that react native 0.61+ handles pod installation for node_modules automatically if devs use a .podspec file for their libraries.

**Comment by tsrnihar** [comment]
@irajwani irajwani  - I am currently facing the same issue. Could you tell me if you have used expo-cli to generate the project?

**Comment by irajwani** [comment]
> @irajwani irajwani - I am currently facing the same issue. Could you tell me if you have used expo-cli to generate the project?

Nope, I'm using classic local cli react native.

**Comment by ravirajar** [comment]
Did anyone fix this issue by creating a project using expo?

**Comment by zendevil** [comment]
I added pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art' in ios/Podfile but I'm getting the same error.

**Comment by bhargav29febgmail** [comment]
install 
npm install @react-native-community/art --save
and run this command
npm install @react-native-community/art --save

**Comment by alirehmanappcrates** [comment]
@baotoan1905 now it's requiring SVG but still not working after installing it

![Screen Shot 2021-09-08 at 1 29 53 PM](https://user-images.githubusercontent.com/86340695/132474656-4bc76532-0d4f-4b5d-b86c-138c4a3a3750.png)

**Comment by ritik2727** [comment]
> Did anyone fix this issue by creating a project using expo?

npm install https://github.com/jzarca01/react-native-chatbot-expo --save

https://github.com/jzarca01/react-native-chatbot-expo

**Comment by banjo09** [comment]
i later had to use react-native-qrcode-svg in my case
