### ISSUE TITLE
Issue removing border from Circle

### ISSUE THREAD

**Issue by halbano** [oblador/react-native-progress#215]
Hey, this is more like a 'Help Request' rather than an issue.

I am trying to implement a layout like in the image below: 

<img width="250" alt="Screen Shot 2020-09-28 at 15 45 15" src="https://user-images.githubusercontent.com/5341623/94472779-9ff61880-01a1-11eb-8d32-825869a91b9f.png">

I have achieved almost what I want but cannot get rid of the external border. 

<img width="294" alt="Screen Shot 2020-09-28 at 15 48 09" src="https://user-images.githubusercontent.com/5341623/94473054-0c711780-01a2-11eb-9a52-c6372d9363f4.png">

Is there a way to remove border from the Circle component? 

Right now my code looks like: 

<pre><code>// Progress must be a value between 0 and 1
export const ProgressCircle = ({ progress, color, width }) => {
	const baseStyleProps = {
		style: styles.progressCircle,
		unfilledColor: Colors.lightGray2,
	};

	return (
		<Progress.Circle
			{...baseStyleProps}
			size={123}
			thickness={7}
			progress={progress}
			color={color}
			strokeCap="round"
		/>
	);
};

export const styles = StyleSheet.create({
	progressCircle: {
		borderRadius: 100,
		borderWidth: 0,
		borderColor: 'transparent',
	},
});</code></pre>

Thanks for your time in advance.

**Comment by halbano** [comment]
I figured out a mistake on my code. Closing this out.

**Comment by Echelpoel** [comment]
Applying `borderWidth={0}` as prop fixes this.
