### ISSUE TITLE
How to use with Expo?

### ISSUE THREAD

**Issue by pedro-surf** [oblador/react-native-progress#216]
I get the following error when trying to run the app in web browser after installing.
![image](https://user-images.githubusercontent.com/40304742/94724990-7835ba80-0331-11eb-8564-a31831a0a2fc.png)

I don't know how to solve this nor if it's still going to work on mobile devices.

More info here: https://github.com/expo/web-examples/issues/73

**Comment by KaniuBillows** [comment]
I have the same issue

**Comment by eero-ms** [comment]
I have the same issue as well.

**Comment by petrbela** [comment]
My guess is something else is wrong with your setup. This library works with Expo for my without any issues, see https://snack.expo.dev/@petrbela/react-native-progress

**Comment by andy-clapham** [comment]
Have you ejected? It's possible there's a problem resolving Utilities/Platform from the react-native-web version.
You could try configuring webpack to handle this file, as per:

https://stackoverflow.com/questions/67943342/error-while-running-web-version-of-react-native-project-web-version-via-expo-th/68831172#68831172
