### ISSUE TITLE
Set Progress.Bar width to 100%

### ISSUE THREAD

**Issue by shivekkhurana** [oblador/react-native-progress#22]
Hello Joel and RNP community,

Thanks for creating and open sourcing such a helpful lib. I'm using it for all my react-native projects.

In one of those projects, I need to set the width of the progress bar to 100%. I did it by passing `width={null}` to progress bar. This sets the width to 100 %, but the progress animation is hindered (gif attached).

![](https://media.giphy.com/media/l2Sq31vbD4zvB8ICI/giphy.gif)

How to go about this ?

Thank you.

**Comment by Zyphrax** [comment]
Setting the width to null seems causes a few rendering issues. I don't think that it is supported :)

@oblador instead of using absolute widths, perhaps it would be a nice idea to use the flex system? For example 60% fill:

```jsx
<View style={{ flexDirection: "row", backgroundColor: "gray" }}>
  <View style={{ flex: 0.6, height: 20, backgroundColor: "green" }} />
  <View style={{ flex: 0.4}} />
 </View>

**Comment by RomanPerin** [comment]
It is great to have a possibility to use flex. Any updates, plans?

**Comment by cwagner22** [comment]
+1, flex should be supported...
I had to use `Dimensions.get('window').width` instead

**Comment by browniefed** [comment]
Percentage based width is now supported, this is how I accomplish it here rather than having to do some sort of flex hack https://github.com/codedailyio/react-native-animated-bar

**Comment by nghiatv** [comment]
use 
```
style={{width: undefined}}
```

Its worked for me

**Comment by shivekkhurana** [comment]
Closing the issue, it's old and seems to be fixed.

**Comment by abuayaan-01** [comment]
Prop : width | Default : 150

Set to null to use automatic flexbox sizing. 

Example: 

```
 <View style={{flex:1}}>
                <Progress.Bar
                  progress={progress}
                  width={null}
                  height={5}
                  color={ProgresssBarColor}
                  borderColor={ProgresssBarBorderColor}
                />
              </View>

```

**Comment by jowmm** [comment]
```
<View className="bg-card w-full rounded-lg p-5 flex flex-row justify-start items-center gap-5">
      <Image source={icon} tintColor={"#14b8a6"} />

      <View className="flex flex-1 flex-col justify-center items-start gap-2 border border-blue-400">
        <Text className="text-white text-xl font-semibold">{"{title}"}</Text>
        <Text className="text-white text-lg font-semibold">{"{amount}"}</Text>
        <Progress.Bar
          progress={0.3}
          width={null}
          color="#14b8a6"
          unfilledColor="#B2DFDB"
        />
      </View>
    </View>
```

<img width="417" height="131" alt="Image" src="https://github.com/user-attachments/assets/ae32c3ef-5014-4756-b945-6c31f881b728" />

width={null} seem to be not working, I already rebuild several times, but still not working

`"react-native-progress": "^5.0.1",`
