### ISSUE TITLE
Exception in HostFunction: Malformed calls from JS: field sizes are different.

### ISSUE THREAD

**Issue by StevieCode** [oblador/react-native-progress#224]
Does anyone have the same issue?

**Comment by StevieCode** [comment]
[[142,129,129,129,71],[0,5,5,5,1],[[51,0,1610915526167,false],[225,{"props":{"style":224},"type":"props"}]],647]
* [native code]:null in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:317:6 in enqueueNativeCall
- node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:139:8 in nonPromiseMethodWrapper
- node_modules/react-native-safe-area-view/index.js:171:3 in SafeView
- node_modules/react-native-safe-area-view/index.js:338:6 in SafeView#_getViewStyles
- node_modules/react-native-reanimated/src/core/AnimatedDebug.js:32:4 in __onEvaluate
- node_modules/react-native-reanimated/src/core/AnimatedDebug.js:12:4 in constructor
- node_modules/react-native-reanimated/src/core/AnimatedParam.js:72:39 in isRunning
* http://packager.3k-vbf.anonymous.hackdavis2021.exp.direct/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:232522:26 in AnimatedComponent
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:7655:17 in constructClassInstance
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:12377:26 in updateClassComponent
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:19181:22 in beginWork$1
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18085:22 in performUnitOfWork
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18013:38 in workLoopSync
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17977:18 in renderRootSync
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17674:33 in performSyncWorkOnRoot
* [native code]:null in performSyncWorkOnRoot
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5321:31 in runWithPriority$argument_1
- node_modules/scheduler/cjs/scheduler.development.js:653:23 in unstable_runWithPriority
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5316:21 in flushSyncCallbackQueueImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5304:28 in flushSyncCallbackQueue
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17125:30 in scheduleUpdateOnFiber
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:7267:16 in classComponentUpdater.enqueueSetState
- node_modules/react/cjs/react.development.js:471:2 in Component.prototype.setState
- node_modules/path-to-regexp/index.js:122:19 in encodeURI.replace$argument_1
* http://packager.3k-vbf.anonymous.hackdavis2021.exp.direct/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:221996:34 in <unknown>
- node_modules/@firebase/firestore/dist/rn/prebuilt.rn-f9cd27ba.js:13798:5 in <anonymous>
- node_modules/@firebase/util/dist/index.esm.js:1081:25 in Sha1.prototype.compress_
- node_modules/@firebase/util/dist/index.esm.js:1189:24 in Sha1.prototype.update
- node_modules/react-native/node_modules/promise/setimmediate/core.js:37:13 in tryCallOne
- node_modules/react-native/node_modules/promise/setimmediate/core.js:123:24 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:181:14 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:441:30 in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:387:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:4 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue

**Comment by StevieCode** [comment]
Putting expression in the progress prop causes the issue. Solved by creating a function that returns the expression value.

**Comment by cloudworkpro-hassen** [comment]
this just started giving me problems 
not sure what to do
I did it two different ways

`
          <Progress.Bar
            // progress={(currentStep && currentStep * 10) / 100} <=-=currentStep is a state
            progress={step()}
            width={350}
            height={15}
            borderRadius={200}
            color="#F59E0B"
            borderColor="#E5E5E5"
            unfilledColor="#FFFFFF"
          />
`

**Comment by Aloynz** [comment]
has anyone resolved this issue?

**Comment by Phong-TH** [comment]
@Aloynz the value put to progress props is NaN causes the issue, just forcing it to 0 if NaN
