### ISSUE TITLE
undefined is not an object evaluating '_reactNativeProgress2.default.Bar'

### ISSUE THREAD

**Issue by Fantasim** [oblador/react-native-progress#25]
Hi,

I'm trying to use react-native-progress-image (with react-native-progress), i've add ART.xcodeproj to my libraries in xcode and link libART.a with libraries in buildphase but when i try with this exemple : 
```
<Image 
    indicator={Progress.Bar}
    indicatorProps={{
         size: 80,
         borderWidth: 0,
         color: 'rgba(150, 150, 150, 1)',
         unfilledColor: 'rgba(200, 200, 200, 0.2)'
    }}
    source={{uri: this.props.url}} 
    style={{height: this.state.height, resizeMode: 'contain'}} 
/>
```

i get this error : 

> undefined is not an object (evaluating '_reactNativeProgress2.default.Bar')
> 2016-09-27 10:02:46.399 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating '_reactNativeProgress2.default.Bar')
> 2016-09-27 10:02:46.490 [warn][tid:com.facebook.react.JavaScript] Possible Unhandled Promise Rejection (id: 0):
> undefined is not an object (evaluating '_reactNativeProgress2.default.Bar')

how can i fix that?

thank's

**Comment by oblador** [comment]
Hi, it looks like you're importing it wrong. Your import statement should look like this: `import * as Progress from 'react-native-progress';`

**Comment by Fantasim** [comment]
Ahah! Ok it works! thanks ;)

**Comment by brimock** [comment]
You might want to update the pie example in the read me:
https://github.com/oblador/react-native-image-progress

it shows 
import Progress from 'react-native-progress';
