### ISSUE TITLE
circle / circleSnail renders with a black fill how to change it with desired color?

### ISSUE THREAD

**Issue by codewitharun** [oblador/react-native-progress#256]
simulator screenshot / same issue in android 
![simulator_screenshot_93053C66-8EF0-4644-96EF-4053F3093A76](https://user-images.githubusercontent.com/51923838/215753794-0666c325-2f94-4fc2-bbd9-21f95434d826.png)

**Comment by Ravi-Seffcon** [comment]
Facing same issue.

**Comment by widianapw** [comment]
I think this is happening because we update the react-native-svg version.

**Comment by symartensv2v** [comment]
I confirm this is occuring because of the react-native-svg mismatching version, try with version: "^12.1.1".

**Comment by kevinantech** [comment]
I also have that problem

**Comment by kevinantech** [comment]
I have the same issue too

**Comment by kevinantech** [comment]
> I confirm this is occuring because of the react-native-svg mismatching version, try with version: "^12.1.1".

yes, in yarn.lock is the version 👍

**Comment by hke-ghtest2** [comment]
I have the same issue too, any workaround on that except changing the version of react-native-svg ?

**Comment by AkbarBakhshi** [comment]
Same issue here.

**Comment by abdullahIsa** [comment]
same here too

**Comment by khaled-osama-elhabibi** [comment]
> I confirm this is occuring because of the react-native-svg mismatching version, try with version: "^12.1.1".

**Comment by simone989** [comment]
This patch should fix the issue:
`diff --git a/node_modules/react-native-progress/Circle.js b/node_modules/react-native-progress/Circle.js
index 79f0a9e..a307a08 100644
--- a/node_modules/react-native-progress/Circle.js
+++ b/node_modules/react-native-progress/Circle.js
@@ -56,6 +56,7 @@ export class ProgressCircle extends Component {
     thickness: 3,
     endAngle: 0.9,
     allowFontScaling: true,
+    fill: 'transparent'
   };
 
   constructor(props, context) {
@@ -168,6 +169,7 @@ export class ProgressCircle extends Component {
           )}
           {border ? (
             <Arc
+            fill={fill}
               radius={size / 2}
               startAngle={0}
               endAngle={(indeterminate ? endAngle * 2 : 2) * Math.PI}
diff --git a/node_modules/react-native-progress/CircleSnail.js b/node_modules/react-native-progress/CircleSnail.js
index cdf2b2d..b1e0b27 100644
--- a/node_modules/react-native-progress/CircleSnail.js
+++ b/node_modules/react-native-progress/CircleSnail.js
@@ -38,6 +38,7 @@ export default class CircleSnail extends Component {
     thickness: 3,
     strokeCap: 'round',
     useNativeDriver: false,
+    fill: 'transparent'
   };
 
   constructor(props) {
@@ -129,6 +130,7 @@ export default class CircleSnail extends Component {
       style,
       thickness,
       strokeCap,
+      fill,
       ...restProps
     } = this.props;
 
@@ -177,6 +179,7 @@ export default class CircleSnail extends Component {
             endAngle={this.state.endAngle}
             strokeCap={strokeCap}
             strokeWidth={thickness}
+            fill={fill}
           />
         </Svg>
         {children}
`

**Comment by Hasham24** [comment]
i am facing the same issue with the latest version of react-native-progress and react-native-svg any solution?

**Comment by kevinantech** [comment]
> i am facing the same issue with the latest version of react-native-progress and react-native-svg any solution? 

https://github.com/oblador/react-native-progress/issues/256#issuecomment-1505026670

**Comment by Hasham24** [comment]
> > i am facing the same issue with the latest version of react-native-progress and react-native-svg any solution?
> 
> [#256 (comment)](https://github.com/oblador/react-native-progress/issues/256#issuecomment-1418275671)

I applied this solution, but then I got an error fabric doesn't support it.

**Comment by dhayaljaswantgit** [comment]
> This patch should fix the issue:
> 
> ```
> diff --git a/node_modules/react-native-progress/Circle.js b/node_modules/react-native-progress/Circle.js
> index 79f0a9e..a307a08 100644
> --- a/node_modules/react-native-progress/Circle.js
> +++ b/node_modules/react-native-progress/Circle.js
> @@ -56,6 +56,7 @@ export class ProgressCircle extends Component {
>      thickness: 3,
>      endAngle: 0.9,
>      allowFontScaling: true,
> +    fill: 'transparent'
>    };
>  
>    constructor(props, context) {
> @@ -168,6 +169,7 @@ export class ProgressCircle extends Component {
>            )}
>            {border ? (
>              <Arc
> +            fill={fill}
>                radius={size / 2}
>                startAngle={0}
>                endAngle={(indeterminate ? endAngle * 2 : 2) * Math.PI}
> diff --git a/node_modules/react-native-progress/CircleSnail.js b/node_modules/react-native-progress/CircleSnail.js
> index cdf2b2d..b1e0b27 100644
> --- a/node_modules/react-native-progress/CircleSnail.js
> +++ b/node_modules/react-native-progress/CircleSnail.js
> @@ -38,6 +38,7 @@ export default class CircleSnail extends Component {
>      thickness: 3,
>      strokeCap: 'round',
>      useNativeDriver: false,
> +    fill: 'transparent'
>    };
>  
>    constructor(props) {
> @@ -129,6 +130,7 @@ export default class CircleSnail extends Component {
>        style,
>        thickness,
>        strokeCap,
> +      fill,
>        ...restProps
>      } = this.props;
>  
> @@ -177,6 +179,7 @@ export default class CircleSnail extends Component {
>              endAngle={this.state.endAngle}
>              strokeCap={strokeCap}
>              strokeWidth={thickness}
> +            fill={fill}
>            />
>          </Svg>
>          {children}
> ```
> 
> I found a pull request that already fixes the problem: https://github.com/oblador/react-native-progress/pull/258/files

This solution worked for me, Thanks :)

**Comment by DaviBFarias** [comment]
Hey guys, I'm sorry about my ignorance, but how can I apply this patch?

manually on the code into node_modules?

**Comment by simone989** [comment]
> Hey guys, I'm sorry about my ignorance, but how can I apply this patch?
> 
> 
> 
> manually on the code into node_modules?
> 
> 
> 
> I did it manually on the files into nodule_modules, it worked for me too, but I don't know if it's the best approach to apply. because if I download the project again and install I will not have this update until it is merged into master in a future version.

https://github.com/ds300/patch-package

**Comment by DaviBFarias** [comment]
> > Hey guys, I'm sorry about my ignorance, but how can I apply this patch?
> > manually on the code into node_modules?
> > I did it manually on the files into nodule_modules, it worked for me too, but I don't know if it's the best approach to apply. because if I download the project again and install I will not have this update until it is merged into master in a future version.
> 
> https://github.com/ds300/patch-package

Thank you so much! It worked like a charm!

**Comment by danielrhodes** [comment]
Just a note, this patch does not work on Pie.

**Comment by Thanaen** [comment]
Quite a crippling bug, as it prevents the use of react-native-svg > 13.8.0, and therefore prevents the use of Fabric :(
Are any maintainers available to check/validate PR  #262 , which seems to solve the problem?

**Comment by Johnrobmiller** [comment]
> I confirm this is occuring because of the react-native-svg mismatching version, try with version: "^12.1.1".

Changing the versions of dependency is a very bad idea. Even if it seems to be working in the short term, you are almost certainly going to cause problems with any other library that needs the latest version of the library you intentionally are using an out of date version of

**Comment by ebulku** [comment]
The easiest way is to change the version of react-native-progress with the PR# fixing this issue in package.json file and run `npm update`

 `"react-native-progress": "oblador/react-native-progress#pull/258/head"`

**Comment by imoempire** [comment]
> The easiest way is to change the version of react-native-progress with the PR# fixing this issue in package.json file and run `npm update`
> 
> `"react-native-progress": "oblador/react-native-progress#pull/258/head"`

This solved the issue

**Comment by oblador** [comment]
Should be fixed in [5.0.1](https://github.com/oblador/react-native-progress/releases/tag/v5.0.1)

**Comment by Thanaen** [comment]
Awesome, thank you @oblador ✌
