### ISSUE TITLE
Android Support?

### ISSUE THREAD

**Issue by dangnelson** [oblador/react-native-progress#3]
https://github.com/facebook/react-native/commit/27ac04742ab4665cd529fe63fd68a30db9293b76
https://github.com/facebook/react-native/releases

**Comment by dangnelson** [comment]
It looks like it's mostly supported as it is. I think there's probably another step that need to happen on Android to get circles and pies working.

**Comment by oblador** [comment]
I tried this out in the simulator yesterday; ART works, but not like the iOS version. All ART based progress indicators are showing up but in a broken way. 

I'm tight on time right now and am not working on any projects for Android so I'd be very happy for some help here :-)

**Comment by lesniakania** [comment]
I think `stokeDash` prop is just ignored on Android :( Resulting in drawing always full circle :(

**Comment by lesniakania** [comment]
Yeah, it looks it's just not ye supported in ART for Android: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/art/ARTShapeShadowNode.java#L186

**Comment by oblador** [comment]
@lesniakania: Thanks for investigating :+1: Let's just wait this one out, it's possible to do a different implementation but it would be a rewrite I just don't have time with right now. Happy to review a PR though!

**Comment by oblador** [comment]
@lesniakania & @dangnelson: Commit https://github.com/oblador/react-native-progress/commit/748fe4d86510f874abd06ebb43a41cc828dda711 refactors away from use of `strokeDash`, but android is still quite broken. If you have the time I'd be grateful if you could debug it – I'm currently not using android myself.

**Comment by lesniakania** [comment]
Hi, I would like to help you, I have some time now for that. But I would appreciate some guidelines from you about idea how this should work. I have little problems with understanding it from the code itself.

I see progress with the progress (;)) but something is indeed still wrong on Android.
Circle is not started from the top or is counter-clockwise. And progress reflected by circle is definitely wrong.
See the picture:
![screen shot 2016-03-30 at 15 32 47](https://cloud.githubusercontent.com/assets/193863/14143646/afa44b5a-f68c-11e5-926d-0053aacd6a45.png)

**Comment by oblador** [comment]
@lesniakania: Actual drawing code for the progress circle is located here: https://github.com/oblador/react-native-progress/blob/master/Shapes/Arc.js

As to what's wrong on android I'm not sure, but this might be related: https://github.com/facebook/react-native/issues/5311 & https://github.com/facebook/react-native/pull/5856

**Comment by dgladkov** [comment]
I am the author of facebook/react-native#5856, can confirm that arc drawing is broken on Android at the moment.

There's a logic error in the code that incorrectly sets arc direction to opposite. Also angles of CCW arcs need to be converted to CW to be displayed properly (Android addArc technically supports CCW drawing direction, but I had weird bugs trying to make it work).

**Comment by lesniakania** [comment]
@dgladkov so you are working on that? I tried changes from  https://github.com/facebook/react-native/pull/5856/files but it does not solve my problem.
Is it something I can do to help?

**Comment by dgladkov** [comment]
@lesniakania the changes fixed my problems with drawing wedges, but there may be some edge cases that I didn't fix. I'm not familiar with this project, could I use example code from the repo to reproduce the bug you're experiencing?

**Comment by dgladkov** [comment]
Tried the example, seems that there's a lot of work to do to support Android:) Even `Progress.Bar` component that doesn't even uses ART suffers facebook/react-native#3198 with child animated view pushing through container with border radius

**Comment by luisfuertes** [comment]
Hi, i have a problem in Android, on iOS my chart works, but on Android the animation doesnt run.

My chart code: 
```
              <View style={{flex: 0.5, alignItems: 'center'}}>
                  <Progress.Circle
                    progress={0}
                    indeterminate={false}
                    color={Commons.Colors.white}
                    unfilledColor={Commons.Colors.overlay}
                    borderWidth={0}
                    size={145}
                    showsText={true}
                  />
              </View>
```

My animation function:
```
    let progress = 0;

    let timer = setInterval(() => {
      progress += 0.01;
      if (progress > maxValue) {
        progress = maxValue;
        clearInterval(timer)
      }

      if(chartType == "data"){
        dispatch(updateDataChart(progress))
      }else if(chartType == "voice"){
        dispatch(updateVoiceChart(progress))
      }
    }, 50);
```

**Comment by luisfuertes** [comment]
And:
```
							<Progress.Bar
								style={{margin: 10}}
								progress={this.props.dataChartProgress}
								indeterminate={false}
								height={30}
								borderRadius={15}
								animated={true}
								unfilledColor={Commons.Colors.opverlay}
								color={Commons.Colors.green_main}
							/>
```

![screenshot_2016-07-06-12-50-57](https://cloud.githubusercontent.com/assets/18212615/16615661/8b9d04f2-4378-11e6-9832-f69a884f9c43.png)

**Comment by luisfuertes** [comment]
You know when it will work on Android?

**Comment by oblador** [comment]
It's [finally here](https://github.com/oblador/react-native-progress/releases/tag/v3.1.0)!

**Comment by gitlovenotwar** [comment]
@luisfuertes I had the same issue on android borderRadius.
