### ISSUE TITLE
No component found for view with name "ARTSurfaceView"

### ISSUE THREAD

**Issue by johnchourajr** [oblador/react-native-progress#31]
![screen shot 2016-10-14 at 2 29 24 pm](https://cloud.githubusercontent.com/assets/6431920/19403266/c948abbc-921a-11e6-832d-bfc3a36fe7aa.png)

I'm getting this screen when I try and add react-native-progress

I ran through the instructions for installation in Xcode, can't seem to get it working. Any suggestions?

My Versions:

```
"react": "15.3.2",
"react-native": "0.35.0",
"react-native-progress": "^3.1.0",
```

This is the code I'm using:

``` javascript
import React, { Component } from 'react'
import {
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  ActivityIndicator
} from 'react-native'
import * as Progress from 'react-native-progress'

export default class Loading extends Component {
  render() {
    return (
      <Progress.CircleSnail
        size={108}
        colors={['red', 'green', 'blue']}
        direction='clockwise'
        thickness={2}
        />
    )
  }
}
```

**Comment by oblador** [comment]
Hi, you must add `ART.xcodeproj` to your project and link with `libART.a`. Compare the example project with yours to spot differences that you missed :-)

**Comment by johnchourajr** [comment]
<img width="960" alt="screen shot 2016-10-15 at 3 53 40 pm" src="https://cloud.githubusercontent.com/assets/6431920/19413863/dee22694-92ef-11e6-8bd1-4fb1acaefece.png">

@oblador I did that. Still not working, is there something with my project that could be throwing it off?

**Comment by oblador** [comment]
Looks good to me, did you recompile?

**Comment by Crash--** [comment]
Your libART.a is not well linked. It appears in red within the Products folder.

**Comment by johnchourajr** [comment]
@oblador Yes, no change.

@Crash-- I've been building from the command line, so I ran the build from *Xcode* to see if this would fix the issue. Doing this made the *libART.a* file no longer red, but didn't fix the issue. I'm working my engineers to try and sort out why this could be happening in our project. Any help with ideas are welcome though.

**Comment by mschipperheyn** [comment]
Is there no way to make sure that this library gets added using react-native link? It kinda sucks to have to do manual stuff. Leads to bugs

**Comment by oblador** [comment]
@mschipperheyn I'm not using `react-native link` as it's quite buggy, but if you want to make a PR I'll accept.

**Comment by mschipperheyn** [comment]
I had a look, but this pod spec is a bit confusing. It's probably something like this, but I'm not sure and I can't spend anymore time on it

    require 'json'
    package_json = JSON.parse(File.read('package.json'))

    Pod::Spec.new do |s|
      s.name         = "react-native-progress"
      s.version      = package_json["version"]
      s.summary      = package_json["description"]
      s.author       = { package_json["author"] => package_json["author"] }
      s.license      = 'MIT'
      s.homepage     = 'https://github.com/oblador/react-native-progress'
      s.source       = { :git => package_json["repository"]["url"] }
      s.platform     = :ios, "7.0"
      s.dependency 'React'
      s.dependency 'React/ART'
    end

**Comment by lakhman** [comment]
I just had this error, I had to simply restart my package manager, I also did a clean in xcode to be sure.

```
react-native start --reset-cache
```

**Comment by sampocs** [comment]
@johnchourajr I'm having the same issue as you and my project looks the same as the screen shot you sent (with libART colored red). Did you ever find a solution?

**Comment by GeorgeCodesigner** [comment]
I have met this problem,and the react config of mine is:"react": "^15.4.1","react-native": "^0.39.2".My xcode is 8.1 and iOS version is 10.1.Did you have found solution of the problem?

**Comment by rascala** [comment]
In case anyone is still having trouble with this.
If your libART.a is red, then the binary is not linked.

I found the solution here
http://browniefed.com/blog/getting-react-art-running-on-react-native/

For posterity, 

1. Select the main project in xcode("open open path/to/projectname.xcodeproj")

1.

**Comment by rascala** [comment]
In case anyone is still having trouble with this.
If your libART.a is red, then the binary is not linked.

I found the solution here
[http://browniefed.com/blog/getting-react-art-running-on-react-native/](url)

For posterity,
1. Select the main project in xcode("open path/to/projectname.xcodeproj" in terminal)
2. Select your main project in the left panel in xcode.
3. Select "Build Phases" from the center view.
4. There will be a section called “Link Binary With Libraries”, expand it, press the + and select libART.a  (This step can only be done after dragging the ART xcodeproj file into Libraries, refer to link for more details)

Hope this helps! :)

**Comment by temitope** [comment]
@johnchourajr @sampocs et. al. i had to upgrade to latest 0.42.0-rc-3. not funnes thing but it worked. more details here - https://github.com/facebook/react-native/issues/11781

**Comment by wvicioso** [comment]
I had this same issue. I fixed by running `react-native upgrade` and resetting all files. Then, I followed step 1 and 2 for linking Binaries on Xcode in RN docs. Running on RN .41

**Comment by oblador** [comment]
Okay, closing this 👍

**Comment by bberak** [comment]
If it helps anyone - I followed the linking instructions, but I was still encountering this issue when running from the simulator using `react-native run-ios`.

After I removed the build folder from my project (`my-project/ios/build`), and re-ran `react-native run-ios`, it worked like a charm.

**Comment by argmn** [comment]
This might help someone as well, while I was struggling with all these suggestions, I found that the order of the libART.a  in the “Link Binary With Libraries” list matters. I had it in the root and only after moving it to the bottom did this start working.

**Comment by jacobo360** [comment]
In my case the ART.xcodeproj wasnt on my directory.. I had to pull it from node_modules/react-native...

**Comment by musicpro** [comment]
Hej,
maybe I am doing something wrong. I develop in Webstorm to build crossplatform. Android is working like a charm. But when I start the iOS App I receive the same error as above. is there a way to link the lib inside Webstom or do I have to switch to xcode for this? Anyone has experience with this or any other ideas?

**Comment by wvicioso** [comment]
@musicpro There probably are some steps you could take to manually link libraries without Xcode. It would require going into you ios folder and adding some code. I don't know what the steps would be. I've always done my manual ios library linking through xcode.

Wish I could offer more help.

**Comment by tony-orn** [comment]
@johnchourajr I had the same issue as you.
Anyone can solve this problem.
Thank you.

**Comment by msageryd** [comment]
@bberak Thank you. I had trouble with this as well. Everything worked after removing the build folder.

**Comment by gabrielmoncea** [comment]
@oblador I am having the same issue with `ARTShape` and `ARTSurfaceView`. Shouldn't it be enough if I install the package through CocoaPods?
