### ISSUE TITLE
Release a new version to include the duration & spinDuration in CircleSnail

### ISSUE THREAD

**Issue by lakhman** [oblador/react-native-progress#37]
Can we release a new version to include the following commit: https://github.com/oblador/react-native-progress/commit/7b402425402a56f630a848f6662e7ab1c4c65434

The above along with pull https://github.com/oblador/react-native-progress/pull/24 for the docs.

The documentation is out of date with the current library release.

**Comment by oblador** [comment]
[Here you go](https://github.com/oblador/react-native-progress/releases/tag/v3.2.0) :-)

**Comment by lakhman** [comment]
Thanks!
