### ISSUE TITLE
Re-applied component

### ISSUE THREAD

**Issue by siwymilek** [oblador/react-native-progress#4]
Component is re-applied on every induction. Can't reset it to initial state.

**Comment by oblador** [comment]
Sorry, I don't know what you mean. Can you elaborate?

**Comment by siwymilek** [comment]
I will try to explain as simple as I can. I placed progress component in single view. I'm opening this view by use Navigator, progress is indicating , then I go back to previous view. Now if I go to view with progress, the progress is already rendered. 
![image](http://i.imgur.com/RQL9epl.jpg)

**Comment by oblador** [comment]
It might be caused by this React Native bug: https://github.com/facebook/react-native/issues/5726
