### ISSUE TITLE
android 系统不支持 overflow 

### ISSUE THREAD

**Issue by snsogbl** [oblador/react-native-progress#44]
android 系统不支持 overflow 。
height borderRadius 设大点的值是 在android手机上会有显示问题

eg:
<Progress.Bar progress={0.3} width={200} borderRadius={20} height={40}/>

**Comment by oblador** [comment]
I don't speak Chinese, sorry.

**Comment by snsogbl** [comment]
The android system does not support overflow.
eg:
<Progress.Bar progress={0.3} width={200} borderRadius={20} height={40}/>

![795ad848-fe2f-4bc9-81b0-98fac47e38fd](https://cloud.githubusercontent.com/assets/5416723/22964671/c6e85de6-f394-11e6-9d1e-bb76f7b41c16.png)

**Comment by grubbyJay** [comment]
@snsogbl 你的问题解决了吗，我也喷到这个问题了
