### ISSUE TITLE
Import issue with react-native-progress after import statment

### ISSUE THREAD

**Issue by cairnsjoe** [oblador/react-native-progress#46]
I am getting the following error:

/node_modules/react-native-progress/index.js: 'import' and 'export' may only appear at the top level (2:0)

I am using ES6 in my REACT component that I am developing. I have done the following import statement that is causing the error:

import * as Progress from 'react-native-progress';

Please let me know what I can do to resolve this issue.

Thank you.

**Comment by oblador** [comment]
Make sure your `.babelrc` file is using the `react-native` preset, it should do so by default unless you've changed it.

**Comment by cairnsjoe** [comment]
Here is what my .babelrc file looks like we also us gulp for our builds and I have also included the config for it I have tried it both ways and get the same error:

.babelrc

{
   "presets": ["es2015", "react", "react-native"]
}


gulp

        .transform("babelify", {presets: ["es2015", "react", "react-native"]})

Error: Parsing file /Users/jcairns/Development Source/UI-Components/node_modules/react-native-progress/index.js: 'import' and 'export' may only appear at the top level (2:0)

**Comment by cairnsjoe** [comment]
This is what is included in my package.json:

  "devDependencies": {
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-react-native": "^1.9.1",
    "babelify": "^7.3.0",

**Comment by oblador** [comment]
Uhm, why are you using gulp for a react native project?

**Comment by cairnsjoe** [comment]
That is what our company management has decided to use. Will this not work for this component?Because it is working for the 40+ other components that we have developed. It should work as long as the dependencies are installed and the presets are there correct? Am I missing anything else?

**Comment by cairnsjoe** [comment]
is there any solution to this issue?

react-native-progress/index.js: 'import' and 'export' may only appear at the top level

**Comment by oblador** [comment]
Hi, unfortunately I'm not going to support this as it's a very uncommon use case for react native. I think you should consider using not gulp in your toolchain as babel transforms are done automatically by packager. I also expect you will run into issues with other third party libraries.
