### ISSUE TITLE
Easing Composition Error for CircleSnail in react-native@0.20

### ISSUE THREAD

**Issue by adelamodwala** [oblador/react-native-progress#5]
It seems that after upgrading to react-native 0.20 the Easing function composition of Easing.quad(Easing.inOut) [in CircleSnail.js] returns an NaN whereas Easing.inOut(Easing.quad) works just fine. Please investigate?

**Comment by oblador** [comment]
Your suggested solution works for both 0.20 and older versions. Released in [2.2.1](https://github.com/oblador/react-native-progress/releases/tag/v2.2.1).
