### ISSUE TITLE
CircleSnail causes unstable rendering component in android

### ISSUE THREAD

**Issue by nhuthuynh** [oblador/react-native-progress#54]
Hi guys,

I am facing with rendering component problem whenever i try to add CircleSnail in some of my screens.  It cause my app unstable rendering component on the screen, some component missing, unexpected behavior ... i tried to run it on debug and release, genymotion and real devices. All the results are same! I post the issue to ask for any solution. Thank in advance !

Here my code and environment

i update my code on gist 

[https://gist.github.com/nhuthuynh/009dee73675c1dbed41d34a86b359057](https://gist.github.com/nhuthuynh/009dee73675c1dbed41d34a86b359057)

Genymotion: 2.9.0
Virtual Devices: Google Nexus 5X - 7.0.0 - API 24 - 1080x1920

**Comment by jaschaio** [comment]
@nhuthuynh I experience similar problems on Android. Did you find a solution or reliable alternative?

**Comment by nhuthuynh** [comment]
@jaschaio: unless the author fixes it, otherwise I recommend using another library component for it. In my case, I used ActivityIndicator and it works perfectly fine.
