### ISSUE TITLE
Android issue when progress is 0

### ISSUE THREAD

**Issue by zoranmarjanovic** [oblador/react-native-progress#58]
There is an issue in android when progress value is 0, because of react-native issue when transform scaleX value is 0. The workaround would be to set progress to 0.001 value, it would be great if you put that in documentation.

**Comment by DemisBand** [comment]
+1

**Comment by oblador** [comment]
Is this still a problem in react native 0.45.1? I cannot reproduce myself.

**Comment by oblador** [comment]
Anyway, duplicate of https://github.com/oblador/react-native-progress/issues/56
