### ISSUE TITLE
Cannot read property 'Surface' of undefined

### ISSUE THREAD

**Issue by andreacab** [oblador/react-native-progress#6]
Hi,

I am using RN 0.14.2 (probably why..but cannot change the version a the moment).

I get the red screen of death when launching the app saying "Cannot read property 'Surface' of undefined" from line 11:0 in Circle.js, even though I have added the .xcodeproject and linked the lib as indicated. Any help/insight is appreciate!
Thanks

**Comment by oblador** [comment]
You must use RN 0.15.0 or later.

**Comment by andreacab** [comment]
Alright, thanks for the quick answer
