### ISSUE TITLE
strokeCap prop on circle not being used by Arc

### ISSUE THREAD

**Issue by byronhallett** [oblador/react-native-progress#63]
I can't see why this is happening from reading the source.

My inspector shows that strokeCap: 'round' is set on progress circle, but the Arc objects below are still 'butt'.

have confirmed using version:
react-native-progress@3.3.0

![screen shot 2017-07-05 at 6 00 07 pm](https://user-images.githubusercontent.com/7391789/27854922-eeb44198-61ab-11e7-9590-d0363367345b.png)
![screen shot 2017-07-05 at 6 00 45 pm](https://user-images.githubusercontent.com/7391789/27854989-22a90182-61ac-11e7-8d9a-c970b906c2b6.png)

**Comment by byronhallett** [comment]
ahh, I see what was wrong. 

My expected behaviour was that the foreground shape would use strokeCap. Is that supposed to be the case? 
Currently, the Circle.js render() function passes strokeCap to the props of the border Arc, but not to the background or foreground arc (the component type named "Shape" within this scope)

Locally, I have added:
strokeCap={strokeCap} 
at Circle.js:150

Should the repo be updated this way too?

**Comment by oblador** [comment]
That sounds wrong yes, care to do a PR?

**Comment by byronhallett** [comment]
No problem, just created #65 

I am going to make a further change to my new fork, since my project wants an open circle like the one below.
Do you think that is something you might want a PR for as well?

![screen shot 2017-07-06 at 11 44 10 am](https://user-images.githubusercontent.com/7391789/27891989-7a06ee14-6240-11e7-919e-f5064784fe4a.png)

**Comment by oblador** [comment]
Fixed in [3.4.0](https://github.com/oblador/react-native-progress/releases/tag/v3.4.0).
