### ISSUE TITLE
Progress.CircleSnail direction

### ISSUE THREAD

**Issue by kolking** [oblador/react-native-progress#7]
It would be nice to add `clockwise` and `counter-clockwise` direction prop for the Progress.CircleSnail

**Comment by lananelson** [comment]
+1

**Comment by lananelson** [comment]
fixed in https://github.com/oblador/react-native-progress/pull/13

**Comment by oblador** [comment]
Released in [3.0.1](https://github.com/oblador/react-native-progress/releases/tag/v3.0.1).
