### ISSUE TITLE
Add text inside progress bar

### ISSUE THREAD

**Issue by mikev10** [oblador/react-native-progress#78]
Is there a way to add text inside of the progress bar?

**Comment by mikev10** [comment]
I figured it out and for anyone else with this question here is how I did it:
`<Progress.Bar progress={0.3} width={200}><Text>test</Text></Progress.Bar>`

**Comment by Jmask** [comment]
Trying to add text to my progress bar and this won't work, maybe something has changed since your post?

**Comment by meyonn** [comment]
Can I ask. is there a way to make a progress bar become a button?

**Comment by sumithtexol** [comment]
When i trying your solution then it's showing like this 
![image](https://user-images.githubusercontent.com/48787926/57966785-45756700-7974-11e9-9ff1-5b05834fa2d3.png)

**Comment by wilywork** [comment]
<Progress.Bar progress={0.3} width={200}>
<Text style={{position:'absolute', flex:0}}>testes</Text>
</Progress.Bar>

**Comment by bilalyaqoob** [comment]
I did like that
<Progress.Bar progress={0.9} color={blueColor} width={200} height={19}>
  <Text style={{alignSelf:"center",color:grayColor,position:"absolute",top:0.5}}>selected week 8</Text>
</Progress.Bar>
