### ISSUE TITLE
Progress Bar overflows when Prop 'progress' set to 1 

### ISSUE THREAD

**Issue by KevinHu2014** [oblador/react-native-progress#9]
`<Progress.Bar progress={this.state.top_progress} 
                   width={200} height={10}
                   color={this.state.top_color} 
                   unfilledColor={'#FFFFFF'} borderWidth={5}
                   borderColor={'#7B7B7B'} />`
![test-mainactivity-05112016170541](https://cloud.githubusercontent.com/assets/7204070/15176572/51773910-179e-11e6-8655-a883de02c3b9.png)
![test-mainactivity-05112016172751](https://cloud.githubusercontent.com/assets/7204070/15176575/54f58704-179e-11e6-8c54-043c3374e61f.png)

**Comment by oblador** [comment]
Fixed in [3.0.0](https://github.com/oblador/react-native-progress/releases/tag/v3.0.0).

**Comment by KevinHu2014** [comment]
Thanks
